version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: ProjectTest-db
    environment:
      POSTGRES_DB: project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"

    networks:
      - project-net
    restart: always

  project:
    image: project
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - project-net
    restart: always

networks:
  project-net:
    driver: bridge
